<?php

if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) {
    exit();
}

$this->setFrameMode(true);

$APPLICATION->IncludeComponent(
    'bitrix:news.detail',
    '',
    [
        'DISPLAY_DATE'              => $arParams['DISPLAY_DATE'],
        'DISPLAY_NAME'              => $arParams['DISPLAY_NAME'],
        'DISPLAY_PICTURE'           => $arParams['DISPLAY_PICTURE'],
        'DISPLAY_PREVIEW_TEXT'      => $arParams['DISPLAY_PREVIEW_TEXT'],
        'IBLOCK_TYPE'               => $arParams['IBLOCK_TYPE'],
        'IBLOCK_ID'                 => $arParams['IBLOCK_ID'],
        'FIELD_CODE'                => $arParams['DETAIL_FIELD_CODE'],
        'PROPERTY_CODE'             => $arParams['DETAIL_PROPERTY_CODE'],
        'DETAIL_URL'                => $arResult['FOLDER'] . $arResult['URL_TEMPLATES']['detail'],
        'SECTION_URL'               => $arResult['FOLDER'] . $arResult['URL_TEMPLATES']['section'],
        'META_KEYWORDS'             => $arParams['META_KEYWORDS'] ?? '-',
        'META_DESCRIPTION'          => $arParams['META_DESCRIPTION'] ?? '-',
        'BROWSER_TITLE'             => $arParams['BROWSER_TITLE'] ?? '-',
        'SET_BROWSER_TITLE'         => 'Y',
        'SET_META_DESCRIPTION'      => 'Y',
        'SET_META_KEYWORDS'         => 'N',
        'SET_CANONICAL_URL'         => 'Y',
        'SET_LAST_MODIFIED'         => $arParams['SET_LAST_MODIFIED'],
        'SET_TITLE'                 => $arParams['SET_TITLE'],
        'MESSAGE_404'               => $arParams['MESSAGE_404'],
        'SET_STATUS_404'            => $arParams['SET_STATUS_404'],
        'SHOW_404'                  => $arParams['SHOW_404'],
        'FILE_404'                  => $arParams['FILE_404'],
        'INCLUDE_IBLOCK_INTO_CHAIN' => $arParams['INCLUDE_IBLOCK_INTO_CHAIN'],
        'ADD_SECTIONS_CHAIN'        => $arParams['ADD_SECTIONS_CHAIN'],
        'ACTIVE_DATE_FORMAT'        => $arParams['DETAIL_ACTIVE_DATE_FORMAT'],
        'CACHE_TYPE'                => 'A',
        'CACHE_TIME'                => $arParams['CACHE_TIME'],
        'CACHE_GROUPS'              => $arParams['CACHE_GROUPS'],
        'USE_PERMISSIONS'           => $arParams['USE_PERMISSIONS'],
        'GROUP_PERMISSIONS'         => $arParams['GROUP_PERMISSIONS'],
        'DISPLAY_TOP_PAGER'         => $arParams['DETAIL_DISPLAY_TOP_PAGER'],
        'DISPLAY_BOTTOM_PAGER'      => $arParams['DETAIL_DISPLAY_BOTTOM_PAGER'],
        'PAGER_TITLE'               => $arParams['DETAIL_PAGER_TITLE'],
        'PAGER_SHOW_ALWAYS'         => 'N',
        'PAGER_TEMPLATE'            => $arParams['DETAIL_PAGER_TEMPLATE'],
        'PAGER_SHOW_ALL'            => $arParams['DETAIL_PAGER_SHOW_ALL'],
        'CHECK_DATES'               => $arParams['CHECK_DATES'],
        'ELEMENT_ID'                => $arResult['VARIABLES']['ELEMENT_ID'],
        'ELEMENT_CODE'              => $arResult['VARIABLES']['ELEMENT_CODE'],
        'SECTION_ID'                => $arResult['VARIABLES']['SECTION_ID'],
        'SECTION_CODE'              => $arResult['VARIABLES']['SECTION_CODE'],
        'IBLOCK_URL'                => $arResult['FOLDER'] . $arResult['URL_TEMPLATES']['news'],
        'ADD_ELEMENT_CHAIN'         => $arParams['ADD_ELEMENT_CHAIN'],
        'STRICT_SECTION_CHECK'      => $arParams['STRICT_SECTION_CHECK'],
        'CSS_CLASS_BODY'            => 'service-detail-page guide-detail-page',
        'CSS_CLASS_HEADER'          => 'default-main-block-header full-width',
        'HEADER_TEXT_CONTAINER'     => 'header-next-content',
    ],
    $component,
);
